uni.bocconi.social-science: # {group_id}.{name} from the knime.yml
  src: <LOCAL_PATH_TO>\\knime-python-social-science # Path to folder containing the extension files
  conda_env_path: <LOCAL_PATH_TO>/.pixi/envs/default # Path to the Python environment to use (use an absolute path)
  debug_mode: false # Optional line, if set to true, it will always use the latest changes of execute/configure, when that method is used within the KNIME Analytics Platform
